### ISSUE TITLE
Deployment with docker compose

### ISSUE THREAD

**Issue by felixsteinke** [hft-rcpsp-scheduling/rcpsp-data-provider#17]
## Tasks

Improve the deployment action:
- [x]  copy `docker-compose-prod.yml` to the server via ssh as `docker-compose.yml` ([docker-compose-prod.yml](https://github.com/hft-rcpsp-scheduling/rcpsp-data-provider/blob/felix/db-v2/docker-compose-prod.yml)). Probably you can use something like SCP or just download it via shell from github.
- [x] execute the `docker compose rm --stop --force`, `docker compose pull` and `docker compose up -d`

This should be done to quickly fix the automated deployment, after merging the #16.

**Comment by FlorianGrabowski** [comment]
`curl -H 'Accept: application/vnd.github.v4.raw' -O -L https://api.github.com/repos/hft-rcpsp-scheduling/rcpsp-data-provider/contents/src/main/resources/makespans/j120hrs.sm`

**Comment by FlorianGrabowski** [comment]
https://stackoverflow.com/questions/18126559/how-can-i-download-a-single-raw-file-from-a-private-github-repo-using-the-comman
