### ISSUE TITLE
Database as docker container

### ISSUE THREAD

**Issue by mrvxk** [hft-rcpsp-scheduling/rcpsp-data-provider#6]
As a Developer I would like to use the required database inside a docker container so I don't have to install mysql on my local machine.

## Background information:
A direct installation is not always desired or may conflict with local installations. Therefore, an isolated Docker instance of database should solve the problem.

## Acceptance Criteria:
1. Easy-to-use command or script to start the database container
2. data-provider is configured to use the database container
3. Data is persisted and still present when container gets deleted
4. Start and Stop Scripts to manage the container (optional)

**Comment by felixsteinke** [comment]
Related to #4. Your suggestions will be taken into account.
